allowBuilds:
  '@apollo/protobufjs': true
  '@nestjs/core': false
  '@prisma/engines': false
  '@scarf/scarf': false
  bcrypt: false
  msgpackr-extract: set this to true or false
  prisma: false
  unrs-resolver: false
