-- This migration is intentionally empty.
-- The invitation, conversation, and message schema changes were already
-- applied in earlier migrations and are kept there to avoid duplicates during reset.
